### save staff
POST http://localhost:8080/staff/add
Content-Type: application/json

{
  "staffName": "Charan",
  "staffEmail": "Charan@gmail.com",
  "staffPass": "Charan"
}

### delete staff
DELETE http://localhost:8080/staff/del?staffId=Staff:9f2e07c2-5c02-4d0d-a4fb-f52489e3bd70
Authorization: Basic jessi@gmail.com jessi

### staff login
POST http://localhost:8080/staff/login
Content-Type: application/json

{
  "staffEmail": "charan@gmail.com",
  "staffPass": "char0an"
}

### ADD EVENT
POST http://localhost:8080/event/addEvent
Content-Type: application/json

{
  "eventName": "eventName_fce6509262b4",
  "eventVenue": "eventVenue_021fcf23a051",
  "eventDate": "2024-11-28 22:38:36",
  "eventDescription": "eventDescription_192f809d831f"
}



